
paths:
  
    
  
    
  - source: /etc/module-content/data/content
    target: /home/ou/TM351-22J/content
    overwrite: never
    
  
    
  
    
  - source: /etc/module-content/data/.jupyter
    target: /home/ou/TM351-22J/.jupyter
    overwrite: never
    
  
    
  - source: /etc/module-content/data/.jupyter/custom
    target: /home/ou/TM351-22J/.jupyter/custom
    overwrite: always
    
  
    
  
    
  
    
  


scripts:
  
    startup:
      
        
      - cmd: mkdir -p openrefine
        
      
  
  


services:
  
  - postgresql
  
  - mongod
  
