name: Docker Container Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Base Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-venv
        pip3 install poetry git+https://github.com/mmh352/ou-container-builder.git
    - name: Generate the Dockerfile
      run: |
        ou-container-builder --no-build
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERACCESSTOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags:  ousefuldemos/oucb-tm351-test:latest
        context: .